### ISSUE TITLE
web ブラウザの互換性

### ISSUE THREAD

**Issue by ykHakata** [HackerzLab/training_hackerzlab#23]
2019/07/08
Microsoft Edge だと一部うまく表示されない問題がある
あわせてどこまで互換性を対応するかの線引きはしておく

2019/08/13
webブラウザの互換性についてはフロントサイドのjsはブートストラップ(iqueryベース)になっているので最低限度の互換性は担保している。これ以上の互換性を求めると、コミュニティーで対応できる内容ではなくなるので、互換性の問題はこれ以上対応しない。

エクサキッズ用の拡張においてエクサメニュー画面のリロードをすると大量にリクエストが発生して、挙動がおかしくなる問題はwebブラウザの互換性ということではないのでそれは別件で対応する

参考: #34

**Comment by arupakan125** [comment]
Internet Explorer11でも同様の事象を確認しています。
リロードの処理がかなり負荷になっている&リロードのたびに一番上に戻されるような感じです。
